Add new shared classes
RauschRobin/AdvancedSoftwareEngineering pull request #26
Opened 2023-11-14 20:20 UTC by MrMaslowski

2023-11-15 08:02 UTC, RauschRobin requested changes
Please do not push trash ❤️

2023-11-15 08:02 UTC, RauschRobin commented on src/preferences.yaml
> +  weather-api-key: ""
Hier kommen nur User spezifische Daten rein. Also keine API Keys außer die sind auf den User spezifisch, was sie in diesen Fällen nicht sind

2023-11-15 08:03 UTC, RauschRobin commented on src/core/shared/WeatherAPI/weather.py
> +    def __new__(cls, *args, **kwargs):
Sollten wir vielleicht mal in Teams besprechen. Für jetzt kannst du es auch mal noch stehen lassen

2023-11-15 08:04 UTC, RauschRobin commented on src/core/shared/Chat_GPT/Chat_Maker.py
Und Tests fehlen auch noch!

2023-11-15 09:06 UTC, MrMaslowski commented on src/core/shared/WeatherAPI/weather.py
> +    def __new__(cls, *args, **kwargs):
Ja ist Singleton. Als ich gegoogelt habe, fande ich dass das am simplesten aussah.

2023-11-15 09:08 UTC, MrMaslowski commented on src/core/shared/WeatherAPI/weather.py
> +         return False
Ja entweder das Wetter ist gesetzt und aktuell oder es ist noch nicht gesetzt oder veraltet

2023-11-15 09:16 UTC, RauschRobin commented on src/core/shared/Chat_GPT/Chat_Maker.py
> +if __name__ == "__main__":
oder auskommentieren wenn du den noch brauchst

2023-11-17 08:10 UTC, RauschRobin approved these changes

2023-11-17 08:10 UTC, merged